sudo: false
dist: trusty

# The version is actually determined by SBT but we want the
# latest image anyway
language: scala
scala: 2.12.8


refs:
  - &bundle
    stage: bundle
    script:
      - ./tools/sbt/bin/sbt assembly

  - &bench
    stage: benchmark
    script:
      - ./tools/sbt/bin/sbt assembly
      - 'java -jar ./target/renaissance-0.1.jar --raw-list | tr -d , >list.txt'
      - 'for BENCH in `cat list.txt`; do echo "====> $BENCH"; java -Xms2500M -Xmx2500M -jar ./target/renaissance-0.1.jar -r 1 "$BENCH" || exit 1; done'

jobs:
  include:
    - stage: "Basic checks"
      name: "Check style"
      script:
        - ./tools/sbt/bin/sbt renaissanceFormatCheck

    - stage: "Basic checks"
      name: "README.md is up to date"
      script:
        - ./tools/sbt/bin/sbt assembly
        - java -jar ./target/renaissance-0.1.jar --readme && git diff --exit-code -- README.md CONTRIBUTION.md

    - <<: *bundle
      os: osx
    - <<: *bundle
      jdk: openjdk8
    - <<: *bundle
      jdk: oraclejdk8

    - <<: *bench
      os: osx
    - <<: *bench
      jdk: openjdk8
    - <<: *bench
      jdk: oraclejdk8

stages:
  - "Basic checks"
  - bundle
  - benchmark

before_script:
  # For us, the default options are broken as they pass "-v"
  # to the JVM instead after the sbt JAR.
  - unset SBT_OPTS

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  # (see https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html#Caching)
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
