sudo: false
dist: trusty

# The version is actually determined by SBT but we want the
# latest image anyway
language: scala
scala: 2.12.8


matrix:
  include:
    # Bundle build (add more JDKs here eventually)
    - os: linux
      jdk: openjdk8

    # Formatting check
    - os: linux
      jdk: openjdk8
      env:
        - CHECKSTYLE=yes

    # Each benchmark
    # The following command prepares the actual entries
    # java -jar target/scala-2.12/renaissance-0.1.jar --raw-list \
    # | sed 's#.*#    - os: linux\n      jdk: openjdk8\n      env:\n        - BENCHMARK=&\n#'
    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=akka-uct

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=chi-square

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=dec-tree

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=dotty

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=dummy

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=finagle-http

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=fj-kmeans

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=future-genetic

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=gauss-mix

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=log-regression

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=mnemonics

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=movie-lens

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=naive-bayes

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=neo4j-analytics

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=page-rank

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=par-mnemonics

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=philosophers

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=rx-scrabble

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=scala-k-means

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=scala-stm-bench7

    - os: linux
      jdk: openjdk8
      env:
        - BENCHMARK=scrabble


before_install:
  - java -version

before_script:
  # For us, the default options are broken as they pass "-v"
  # to the JVM instead after the sbt JAR.
  - unset SBT_OPTS

script:
  - 'if [ "$CHECKSTYLE" = "yes" ]; then ./tools/sbt/bin/sbt renaissanceFormatCheck; travis_terminate $?; fi'
  - ./tools/sbt/bin/sbt assembly
  - 'if [ -n "$BENCHMARK" ]; then java -jar ./target/scala-2.12/renaissance-0.1.jar -r 1 $BENCHMARK; fi'
