sudo: false
dist: trusty
language: scala

matrix:
  include:
#    - os: linux
#      scala: 2.9.3
#    - os: linux
#      scala: 2.10.6
    - os: linux
      scala: 2.10.6
      jdk: oraclejdk9
      env:
        - BENCHMARK=scala-k-means  

before_install:
  - java -version

script:
  - ./tools/sbt/bin/sbt renaissanceBundle
  - 'if [ -n "$BENCHMARK" ]; then java -cp `ls target/renaissance/jars/*.jar | paste -sd:` org.renaissance.RenaissanceSuite -r 1 $BENCHMARK; fi'
